<?php

namespace Dna;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-24 at 16:10:28.
 */
class DnaBaseTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DnaBase
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DnaBase;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Dna\DnaBase::getVersion
     * @todo   Implement testGetVersion().
     */
    public function testGetVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dna\DnaBase::getFrameworkPath
     * @todo   Implement testGetFrameworkPath().
     */
    public function testGetFrameworkPath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dna\DnaBase::initialize
     * @todo   Implement testInitialize().
     */
    public function testInitialize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
