<?php

namespace Dna;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-24 at 16:10:28.
 */
class DnaTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Dna
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Dna;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
