<?php

namespace Dna\Utils;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-24 at 16:10:31.
 */
class ArrayMethodsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ArrayMethods
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ArrayMethods;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Dna\Utils\ArrayMethods::clean
     * @todo   Implement testClean().
     */
    public function testClean() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dna\Utils\ArrayMethods::trim
     * @todo   Implement testTrim().
     */
    public function testTrim() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dna\Utils\ArrayMethods::first
     * @todo   Implement testFirst().
     */
    public function testFirst() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dna\Utils\ArrayMethods::last
     * @todo   Implement testLast().
     */
    public function testLast() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dna\Utils\ArrayMethods::toObject
     * @todo   Implement testToObject().
     */
    public function testToObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dna\Utils\ArrayMethods::flatten
     * @todo   Implement testFlatten().
     */
    public function testFlatten() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dna\Utils\ArrayMethods::toQueryString
     * @todo   Implement testToQueryString().
     */
    public function testToQueryString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
