<?php

namespace Dna\Utils;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-24 at 16:10:30.
 */
class StringMethodsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var StringMethods
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new StringMethods;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Dna\Utils\StringMethods::getDelimiter
     * @todo   Implement testGetDelimiter().
     */
    public function testGetDelimiter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dna\Utils\StringMethods::setDelimiter
     * @todo   Implement testSetDelimiter().
     */
    public function testSetDelimiter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dna\Utils\StringMethods::match
     * @todo   Implement testMatch().
     */
    public function testMatch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dna\Utils\StringMethods::split
     * @todo   Implement testSplit().
     */
    public function testSplit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dna\Utils\StringMethods::sanitize
     * @todo   Implement testSanitize().
     */
    public function testSanitize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dna\Utils\StringMethods::unique
     * @todo   Implement testUnique().
     */
    public function testUnique() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dna\Utils\StringMethods::indexOf
     * @todo   Implement testIndexOf().
     */
    public function testIndexOf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dna\Utils\StringMethods::lastIndexOf
     * @todo   Implement testLastIndexOf().
     */
    public function testLastIndexOf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dna\Utils\StringMethods::singular
     * @todo   Implement testSingular().
     */
    public function testSingular() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dna\Utils\StringMethods::plural
     * @todo   Implement testPlural().
     */
    public function testPlural() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
